#!/bin/sh
cd /opt
chgrp -R staff cos
chmod -R 775 cos/etc
chmod g+s cos/etc
cd /usr/local/bin
ln -s /opt/cos/bin/* .
mkdir -p /usr/local/sbin
cd /usr/local/sbin
ln -s /opt/cos/sbin/* .
cd
show-sn
show-model
show-tag
if [ "$SUDO_USER" == "cosadm" ]
  then
     echo "cosadm"
     # cat /opt/cos/info/crontab.txt | crontab -
  else
     echo "NOT cosadm"
     chown -R $SUDO_USER:staff /opt/cos
     chown -R $SUDO_USER:staff /usr/local/bin
     chown -R $SUDO_USER:staff /usr/local/sbin
fi
