#!/bin/bash

## Assumptions:  
# /usr/local/bin  -- Owned by Primary User
# /usr/local/sbin -- Owndge by Prmary User
# /opt/cos        -- Writable by Primary User
#
## Fix '$ sudo chmod -R $USER /usr/local/bin /usr/local/sbin'

# Define the repository URL and local path
repoUrl="https://github.com/ncsu-cos-it/mac"
localPath="/opt/cos"

# Check if the local repository exists
if [ -d $localPath ] 
  then 
    # If it exists, navigate to the repository and pull the latest changes
    # echo "Repository exists. Pulling latest changes..."
    cd $localPath
    git pull $localPath
  else 
    # If it doesn't exist, clone the repository
    # echo "Repository does not exist. Cloning repository..."
    git clone $repoUrl $localPath
    chmod -R 775 /opt/cos/etc
    chmod g+s /opt/cos/etc
    chgrp -R staff /opt/cos
    cat /opt/cos/info/crontab.txt | crontab -
    if ! [ -d "/usr/local/sbin" ] 
      then
	 mkdir /usr/local/sbin
    fi
fi
ln -f -s /opt/cos/bin/* /usr/local/bin/
ln -f -s /opt/cos/sbin/* /usr/local/sbin/
