#!/bin/bash

# Check if user is root
if [ ! "$(id -u)" -eq 0 ]; then
   echo sudo required
   exit 0
fi

cd /Users
Users=`ls -1 | grep -v $SUDO_USER | grep -v .localized | grep -v Shared | grep -v cos`
for a in ${Users}
do
	echo Deleting User [ $a ]
	sysadminctl -deleteUser $a
done    
