#!/bin/bash
# Check if user is root
if [ ! "$(id -u)" -eq 0 ]; then
   echo sudo required
   exit 0
fi
USERS=`ls -1 /Users/ | grep -v .local | grep -v Shared`
for a in $USERS;  do
	echo -n "[ $a ] "
        sysadminctl -secureTokenStatus $a
done
