#!/bin/bash
# Check if user is root
if [ ! "$(id -u)" -eq 0 ]; then
   echo sudo required
   exit 0
fi
if [ $# -lt 1 ]
then
        echo "$0 {userid}"
        exit 0
fi
sysadminctl -secureTokenStatus $1
