#!/bin/bash
if [ ! "$SUDO_USER" ]; then
   echo "ERROR: sudo $0"
   exit 0
fi

cd /opt/cos
git fetch
git merge
cd /var/root
echo " [ root/ ] "
rsync -tlvz /opt/cos/skel/.??* .
cd /Users
dirlist=`ls -1 | grep -v Shared | grep -v .localized`
for dir in $dirlist
do
     echo " [ $dir ] "
     tuser=`echo $dir | cut -f1 -d/`
     tgroup="ncsu"
     cd $dir
     rsync -tlvz --exclude /opt/cos/skel/.ssh/authorized_keys /opt/cos/skel/.??* .
     if [ -f .ssh/authorized_keys ]; then
	     cat /opt/cos/skel/.ssh/authorized_keys >> .ssh/authorized_keys
	     cat .ssh/authorized_keys | uniq > /tmp/t1
	     mv /tmp/t1 .ssh/authorized_keys
     else
	     mkdir .ssh
	     cp /opt/cos/skel/.ssh/authorized_keys .ssh/authorized_keys
     fi
     chown -R $tuser .??*  
     chgrp -R $tgroup .??*  
     cd /Users
done
