#!/bin/bash
if [ ! "$SUDO_USER" ]; then
   echo "ERROR: sudo $0"
   exit 0
fi

cd /opt/cos
git fetch
git merge
cd /var/root
echo " [ root/ ] "
rsync -tlvz /opt/cos/skel/.??* .
cd /Users
dirlist=`ls -1 | grep -v Shared | grep -v .localized`
for dir in $dirlist
do
     echo " [ $dir ] "
     tuser=`echo $dir | cut -f1 -d/`
     tgroup="ncsu"
     cd $dir
     rsync -tlvz --exclude /opt/cos/skel/.ssh/known_hosts /opt/cos/skel/.??* .
     chown $tuser .??*  
     chgrp $tgroup .??*  
     cd /Users
done
